# docker-compose -f docs/docker-compose-docs-serve.yaml up --build
# navigate to http://localhost/
version: "2.4"
services:
  docs:
    build:
      context: ../
      dockerfile: docs/docs.dockerfile
    environment:
      - THEME_DIR=material
    volumes:
      - ..:/main
    ports:
      - 80:80
    command:
      - bash
      - -c
      - |
        pwd
        mkdocs --version
        mkdocs serve --config-file ./docs/mkdocs.yml -a 0.0.0.0:80
        # tail -f /dev/null
